export { default as CoverVideo } from './CoverVideo' 
export { default as Logo } from './Logo'
export { default as AboutUs } from './AboutUs'
export { default as Shop } from './Shop' 
export { default as ScrollTriggerProxy } from './ScrollTriggerProxy'
export { default as Product } from './Product'
export { default as Banner } from './Banner'